name: 'Create a Release by file'
description: 'Create a release for a tag in your repository'
author: 'GitHub'
inputs:
  release_file_path:
    description: 'The path of the file. This file should include release note by Markdown format.'
    required: false
    default: 'RELEASE.md'
outputs:
  id:
    description: 'The ID of the created Release'
  html_url:
    description: 'The URL users can navigate to in order to view the release'
  upload_url:
    description: 'The URL for uploading assets to the release'
runs:
  using: 'node12'
  main: 'main.js'
branding:
  icon: 'tag'
  color: 'gray-dark'